name: Deploy Web App to GitHub Pages

on:
  push:
    tags:
    - 'v*'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  call_build_app:
    uses: ./.github/workflows/build-app.yml
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
      ref_name: ${{ github.ref_name }}
      ref_type: ${{ github.ref_type }}

  call_deploy_gh_pages:
    needs:
    - call_build_app
    uses: ./.github/workflows/deploy-gh-pages.yml
    secrets: inherit
    with:
      ref_name: ${{ github.ref_name }}

  call_deploy_gh_releases:
    needs:
    - call_deploy_gh_pages
    uses: ./.github/workflows/deploy-gh-releases.yml
    secrets: inherit
    with:
      ref_name: ${{ github.ref_name }}
